{
  "openapi": "3.0.0",
  "info": {
    "description": "The Microsoft Azure Network management API provides a RESTful set of web services that interact with Microsoft Azure Networks service to manage your network resources. The API has entities that capture the relationship between an end user and the Microsoft Azure Networks service.",
    "title": "NetworkManagementClient",
    "version": "2018-12-01",
    "x-apisguru-categories": ["cloud"],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_assets.onestore.ms_cdnfiles_onestorerolling-1606-01000_shell_v3_images_logo_microsoft.png"
    },
    "x-origin": [
      {
        "format": "swagger",
        "url": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/network/resource-manager/Microsoft.Network/stable/2018-12-01/virtualNetworkTap.json",
        "version": "2.0"
      }
    ],
    "x-preferred": true,
    "x-providerName": "azure.com",
    "x-serviceName": "network-virtualNetworkTap",
    "x-tags": ["Azure", "Microsoft"]
  },
  "security": [{ "azure_auth": ["user_impersonation"] }],
  "paths": {
    "/subscriptions/{subscriptionId}/providers/Microsoft.Network/virtualNetworkTaps": {
      "get": {
        "description": "Gets all the VirtualNetworkTaps in a subscription.",
        "operationId": "VirtualNetworkTaps_ListAll",
        "parameters": [
          {
            "description": "Client API version.",
            "in": "query",
            "name": "api-version",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "List all virtual network taps": { "value": "2018-12-01" } }
          },
          {
            "description": "The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.",
            "in": "path",
            "name": "subscriptionId",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "List all virtual network taps": { "value": "subid" } }
          }
        ],
        "responses": {
          "200": {
            "description": "Request successful. The operation returns a list of Virtual Network Tap resources.",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/VirtualNetworkTapListResult" },
                "examples": {
                  "List all virtual network taps": { "$ref": "#/components/examples/List_all_virtual_network_taps" }
                }
              }
            }
          }
        },
        "tags": ["VirtualNetworkTaps"],
        "x-ms-pageable": { "nextLinkName": "nextLink" }
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworkTaps": {
      "get": {
        "description": "Gets all the VirtualNetworkTaps in a subscription.",
        "operationId": "VirtualNetworkTaps_ListByResourceGroup",
        "parameters": [
          {
            "description": "The name of the resource group.",
            "in": "path",
            "name": "resourceGroupName",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "List virtual network taps in resource group": { "value": "rg1" } }
          },
          {
            "description": "Client API version.",
            "in": "query",
            "name": "api-version",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "List virtual network taps in resource group": { "value": "2018-12-01" } }
          },
          {
            "description": "The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.",
            "in": "path",
            "name": "subscriptionId",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "List virtual network taps in resource group": { "value": "subid" } }
          }
        ],
        "responses": {
          "200": {
            "description": "Request successful. The operation returns a list of Virtual Network Tap resources.",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/VirtualNetworkTapListResult" },
                "examples": {
                  "List virtual network taps in resource group": {
                    "$ref": "#/components/examples/List_virtual_network_taps_in_resource_group"
                  }
                }
              }
            }
          }
        },
        "tags": ["VirtualNetworkTaps"],
        "x-ms-pageable": { "nextLinkName": "nextLink" }
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworkTaps/{tapName}": {
      "delete": {
        "description": "Deletes the specified virtual network tap.",
        "operationId": "VirtualNetworkTaps_Delete",
        "parameters": [
          {
            "description": "The name of the resource group.",
            "in": "path",
            "name": "resourceGroupName",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Delete Virtual Network Tap resource": { "value": "rg1" } }
          },
          {
            "description": "The name of the virtual network tap.",
            "in": "path",
            "name": "tapName",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Delete Virtual Network Tap resource": { "value": "test-vtap" } }
          },
          {
            "description": "Client API version.",
            "in": "query",
            "name": "api-version",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Delete Virtual Network Tap resource": { "value": "2018-12-01" } }
          },
          {
            "description": "The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.",
            "in": "path",
            "name": "subscriptionId",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Delete Virtual Network Tap resource": { "value": "subid" } }
          }
        ],
        "responses": {
          "200": { "description": "Delete successful." },
          "202": {
            "description": "Accepted. Sets 'Deleting' provisioningState until the operation completes. Returns an operation URI that can be queried to find the current state of the operation."
          },
          "204": { "description": "Request successful. Resource does not exist." }
        },
        "tags": ["VirtualNetworkTap"],
        "x-ms-long-running-operation": true
      },
      "get": {
        "description": "Gets information about the specified virtual network tap.",
        "operationId": "VirtualNetworkTaps_Get",
        "parameters": [
          {
            "description": "The name of the resource group.",
            "in": "path",
            "name": "resourceGroupName",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Get Virtual Network Tap": { "value": "rg1" } }
          },
          {
            "description": "The name of virtual network tap.",
            "in": "path",
            "name": "tapName",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Get Virtual Network Tap": { "value": "testvtap" } }
          },
          {
            "description": "Client API version.",
            "in": "query",
            "name": "api-version",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Get Virtual Network Tap": { "value": "2018-12-01" } }
          },
          {
            "description": "The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.",
            "in": "path",
            "name": "subscriptionId",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Get Virtual Network Tap": { "value": "subid" } }
          }
        ],
        "responses": {
          "200": {
            "description": "Request successful. The operation returns the resulting VirtualNetworkTap resource.",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/VirtualNetworkTap" },
                "examples": { "Get Virtual Network Tap": { "$ref": "#/components/examples/Get_Virtual_Network_Tap" } }
              }
            }
          }
        },
        "tags": ["VirtualNetworkTap"]
      },
      "patch": {
        "description": "Updates an VirtualNetworkTap tags.",
        "operationId": "VirtualNetworkTaps_UpdateTags",
        "parameters": [
          {
            "description": "The name of the resource group.",
            "in": "path",
            "name": "resourceGroupName",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Update virtual network tap tags": { "value": "rg1" } }
          },
          {
            "description": "The name of the tap.",
            "in": "path",
            "name": "tapName",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Update virtual network tap tags": { "value": "test-vtap" } }
          },
          {
            "description": "Client API version.",
            "in": "query",
            "name": "api-version",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Update virtual network tap tags": { "value": "2018-12-01" } }
          },
          {
            "description": "The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.",
            "in": "path",
            "name": "subscriptionId",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Update virtual network tap tags": { "value": "subid" } }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "Tags object for patch operations.",
                "properties": {
                  "tags": {
                    "additionalProperties": { "type": "string" },
                    "description": "Resource tags.",
                    "type": "object"
                  }
                }
              }
            }
          },
          "description": "Parameters supplied to update VirtualNetworkTap tags.",
          "required": true
        },
        "responses": {
          "200": {
            "description": "Update successful. The operation returns the resulting VirtualNetworkTap resource.",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/VirtualNetworkTap" },
                "examples": {
                  "Update virtual network tap tags": { "$ref": "#/components/examples/Update_virtual_network_tap_tags" }
                }
              }
            }
          }
        },
        "tags": ["VirtualNetworkTap"],
        "x-ms-long-running-operation": true
      },
      "put": {
        "description": "Creates or updates a Virtual Network Tap.",
        "operationId": "VirtualNetworkTaps_CreateOrUpdate",
        "parameters": [
          {
            "description": "The name of the resource group.",
            "in": "path",
            "name": "resourceGroupName",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Create Virtual Network Tap": { "value": "rg1" } }
          },
          {
            "description": "The name of the virtual network tap.",
            "in": "path",
            "name": "tapName",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Create Virtual Network Tap": { "value": "test-vtap" } }
          },
          {
            "description": "Client API version.",
            "in": "query",
            "name": "api-version",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Create Virtual Network Tap": { "value": "2018-12-01" } }
          },
          {
            "description": "The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.",
            "in": "path",
            "name": "subscriptionId",
            "required": true,
            "schema": { "type": "string" },
            "examples": { "Create Virtual Network Tap": { "value": "subid" } }
          }
        ],
        "requestBody": {
          "content": { "application/json": { "schema": { "$ref": "#/components/schemas/VirtualNetworkTap" } } },
          "description": "Parameters supplied to the create or update virtual network tap operation.",
          "required": true
        },
        "responses": {
          "200": {
            "description": "Update successful. The operation returns the resulting VirtualNetworkTap resource.",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/VirtualNetworkTap" },
                "examples": {
                  "Create Virtual Network Tap": { "$ref": "#/components/examples/Create_Virtual_Network_Tap" }
                }
              }
            }
          },
          "201": {
            "description": "Create successful. The operation returns the resulting VirtualNetworkTap resource.",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/VirtualNetworkTap" },
                "examples": {
                  "Create Virtual Network Tap": { "$ref": "#/components/examples/Create_Virtual_Network_Tap" }
                }
              }
            }
          }
        },
        "tags": ["VirtualNetworkTap"],
        "x-ms-long-running-operation": true
      }
    }
  },
  "servers": [{ "url": "https://management.azure.com" }],
  "components": {
    "examples": {
      "List_all_virtual_network_taps": {
        "value": {
          "value": [
            {
              "etag": "etag",
              "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworkTaps/testvtap",
              "location": "centraluseuap",
              "name": "testvtap",
              "properties": {
                "destinationNetworkInterfaceIPConfiguration": {
                  "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface/ipConfigurations/testIPConfig1"
                },
                "destinationPort": 4789,
                "networkInterfaceTapConfigurations": [
                  {
                    "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface2/tapConfigurations/testtapConfiguration"
                  }
                ],
                "provisioningState": "Succeded",
                "resourceGuid": "6A7C139D-8B8D-499B-B7CB-4F3F02A8A44F"
              },
              "type": "Microsoft.Network/virtualNetworkTaps"
            },
            {
              "etag": "etag",
              "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworkTaps/testvtap2",
              "location": "centraluseuap",
              "name": "testvtap2",
              "properties": {
                "destinationNetworkInterfaceIPConfiguration": {
                  "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface/ipConfigurations/testIPConfig1"
                },
                "destinationPort": 4789,
                "networkInterfaceTapConfigurations": [
                  {
                    "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface3/tapConfigurations/testtapConfiguration"
                  }
                ],
                "provisioningState": "Succeded",
                "resourceGuid": "6A7C139D-8B8D-499B-B7CB-4F3F02A8A44F"
              },
              "type": "Microsoft.Network/virtualNetworkTaps"
            }
          ]
        }
      },
      "List_virtual_network_taps_in_resource_group": {
        "value": {
          "value": [
            {
              "etag": "etag",
              "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworkTaps/testvtap",
              "location": "centraluseuap",
              "name": "testvtap",
              "properties": {
                "destinationNetworkInterfaceIPConfiguration": {
                  "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface/ipConfigurations/testIPConfig1"
                },
                "destinationPort": 4789,
                "networkInterfaceTapConfigurations": [
                  {
                    "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface2/tapConfigurations/testtapConfiguration"
                  }
                ],
                "provisioningState": "Succeded",
                "resourceGuid": "6A7C139D-8B8D-499B-B7CB-4F3F02A8A44F"
              },
              "type": "Microsoft.Network/virtualNetworkTaps"
            },
            {
              "etag": "etag",
              "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworkTaps/testvtap2",
              "location": "centraluseuap",
              "name": "testvtap2",
              "properties": {
                "destinationNetworkInterfaceIPConfiguration": {
                  "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface/ipConfigurations/testIPConfig1"
                },
                "destinationPort": 4789,
                "networkInterfaceTapConfigurations": [
                  {
                    "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface3/tapConfigurations/testtapConfiguration"
                  }
                ],
                "provisioningState": "Succeded",
                "resourceGuid": "6A7C139D-8B8D-499B-B7CB-4F3F02A8A44F"
              },
              "type": "Microsoft.Network/virtualNetworkTaps"
            }
          ]
        }
      },
      "Get_Virtual_Network_Tap": {
        "value": {
          "etag": "etag",
          "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworkTaps/testvtap",
          "location": "centraluseuap",
          "name": "testvtap",
          "properties": {
            "destinationNetworkInterfaceIPConfiguration": {
              "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface/ipConfigurations/testIPConfig1"
            },
            "destinationPort": 4789,
            "networkInterfaceTapConfigurations": [
              {
                "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface2/tapConfigurations/testtapConfiguration"
              }
            ],
            "provisioningState": "Succeded",
            "resourceGuid": "6A7C139D-8B8D-499B-B7CB-4F3F02A8A44F"
          },
          "type": "Microsoft.Network/virtualNetworkTaps"
        }
      },
      "Update_virtual_network_tap_tags": {
        "value": {
          "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworkTaps/test-vtap",
          "location": "eastus",
          "name": "test-vtap",
          "properties": {
            "destinationNetworkInterfaceIPConfiguration": {
              "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface/ipConfigurations/testIPConfig1"
            },
            "destinationPort": 4789,
            "networkInterfaceTapConfigurations": [
              {
                "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface2/tapConfigurations/testtapConfiguration"
              }
            ],
            "provisioningState": "Succeded"
          },
          "tags": { "tag1": "value1", "tag2": "value2" },
          "type": "Microsoft.Network/virtualNetworkTaps"
        }
      },
      "Create_Virtual_Network_Tap": {
        "value": {
          "etag": "etag",
          "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworkTaps/testvtap",
          "location": "centraluseuap",
          "name": "testvtap",
          "properties": {
            "destinationNetworkInterfaceIPConfiguration": {
              "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface/ipConfigurations/testIPConfig1"
            },
            "destinationPort": 4789,
            "networkInterfaceTapConfigurations": [
              {
                "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface2/tapConfigurations/testtapConfiguration"
              }
            ],
            "provisioningState": "Succeded",
            "resourceGuid": "6A7C139D-8B8D-499B-B7CB-4F3F02A8A44F"
          },
          "type": "Microsoft.Network/virtualNetworkTaps"
        }
      }
    },
    "parameters": {
      "ApiVersionParameter": {
        "description": "Client API version.",
        "in": "query",
        "name": "api-version",
        "required": true,
        "schema": { "type": "string" }
      },
      "SubscriptionIdParameter": {
        "description": "The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.",
        "in": "path",
        "name": "subscriptionId",
        "required": true,
        "schema": { "type": "string" }
      }
    },
    "securitySchemes": {
      "azure_auth": {
        "description": "Azure Active Directory OAuth2 Flow",
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/authorize",
            "scopes": { "user_impersonation": "impersonate your user account" }
          }
        }
      }
    },
    "schemas": {
      "VirtualNetworkTap": {
        "allOf": [
          {
            "description": "Common resource representation.",
            "properties": {
              "id": { "description": "Resource ID.", "type": "string" },
              "location": { "description": "Resource location.", "type": "string" },
              "name": { "description": "Resource name.", "readOnly": true, "type": "string" },
              "tags": {
                "additionalProperties": { "type": "string" },
                "description": "Resource tags.",
                "type": "object"
              },
              "type": { "description": "Resource type.", "readOnly": true, "type": "string" }
            },
            "x-ms-azure-resource": true
          }
        ],
        "description": "Virtual Network Tap resource",
        "properties": {
          "etag": {
            "description": "Gets a unique read-only string that changes whenever the resource is updated.",
            "type": "string"
          },
          "properties": { "$ref": "#/components/schemas/VirtualNetworkTapPropertiesFormat" }
        }
      },
      "VirtualNetworkTapListResult": {
        "description": "Response for ListVirtualNetworkTap API service call.",
        "properties": {
          "nextLink": { "description": "The URL to get the next set of results.", "type": "string" },
          "value": {
            "description": "A list of VirtualNetworkTaps in a resource group.",
            "items": { "$ref": "#/components/schemas/VirtualNetworkTap" },
            "type": "array"
          }
        }
      },
      "VirtualNetworkTapPropertiesFormat": {
        "description": "Virtual Network Tap properties.",
        "properties": {
          "destinationLoadBalancerFrontEndIPConfiguration": {
            "$ref": "./loadBalancer.json#/definitions/FrontendIPConfiguration"
          },
          "destinationNetworkInterfaceIPConfiguration": {
            "$ref": "./networkInterface.json#/definitions/NetworkInterfaceIPConfiguration"
          },
          "destinationPort": {
            "description": "The VXLAN destination port that will receive the tapped traffic.",
            "type": "integer"
          },
          "networkInterfaceTapConfigurations": {
            "description": "Specifies the list of resource IDs for the network interface IP configuration that needs to be tapped.",
            "items": { "$ref": "./networkInterface.json#/definitions/NetworkInterfaceTapConfiguration" },
            "readOnly": true,
            "type": "array"
          },
          "provisioningState": {
            "description": "The provisioning state of the virtual network tap. Possible values are: 'Updating', 'Deleting', and 'Failed'.",
            "readOnly": true,
            "type": "string"
          },
          "resourceGuid": {
            "description": "The resourceGuid property of the virtual network tap.",
            "readOnly": true,
            "type": "string"
          }
        }
      }
    }
  }
}
